apps/blog/urls.py
from django.urls import path, include
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.home, name='home'),  # 主页
    path('article/<int:pk>', views.detail, name='article_detail'),  # 文章详情
    path('category/<int:pk>', views.search_category, name='search_category'),  # 分类搜索
    path('tag/<str:tag>', views.search_tag, name='search_tag'),  # 标签搜索
    path('archives/<str:year>/<str:month>/<str:day>', views.archives, name='archives'),  # 按日归档
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.blog import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.blog.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/blog/models.py
from django.db import models

from django.utils.timezone import now


class Tag(models.Model):
    name = models.CharField(verbose_name='标签名', max_length=64)
    created_time = models.DateTimeField(verbose_name='创建时间', default=now)
    updated_time = models.DateTimeField(verbose_name='修改时间', default=now)

    # 使对象在后台显示更友好
    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name = '标签名称'  # 指定后台显示模型名称
        verbose_name_plural = '标签列表'  # 指定后台显示复数名称
        db_table = 'tag'  # 数据库表名


class Category(models.Model):
    name = models.CharField(verbose_name='类别名称', max_length=64)
    created_time = models.DateTimeField(verbose_name='创建时间', default=now)
    updated_time = models.DateTimeField(verbose_name='修改时间', default=now)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name = '类别名称'
        verbose_name_plural = '分类列表'
        db_table = 'category'


class Article(models.Model):
    STATUS_CHOICES = (
        ('d', '草稿'),
        ('p', '发表'),
    )
    title = models.CharField(verbose_name='标题', max_length=100)
    content = models.TextField(verbose_name='正文', blank=True, null=True)
    status = models.CharField(verbose_name='状态', max_length=1, choices=STATUS_CHOICES, default='p')
    views = models.PositiveIntegerField(verbose_name='浏览量', default=0)
    created_time = models.DateTimeField(verbose_name='创建时间', default=now)
    pub_time = models.DateTimeField(verbose_name='发布时间', blank=True, null=True)
    updated_time = models.DateTimeField(verbose_name='修改时间', default=now)
    category = models.ForeignKey(Category, verbose_name='分类', on_delete=models.CASCADE, blank=False, null=False)
    tags = models.ManyToManyField(Tag, verbose_name='标签集合', blank=True)

    # 使对象在后台显示更友好
    def __str__(self):
        return self.title

    # 更新浏览量
    def viewed(self):
        self.views += 1
        self.save(update_fields=['views'])

    # 下一篇
    def next_article(self):  # id比当前Id大，状态为已发布，发布时间不为空
        return Article.objects.filter(id__gt=self.id, status='p', pub_time__isnull=False).first()

    # 上一篇
    def prev_article(self):  # id比当前Id小，状态为已发布，发布时间不为空
        return Article.objects.filter(id__lt=self.id, status='p', pub_time__isnull=False).first()

    class Meta:
        ordering = ['-pub_time']  # 按文章的发表时间降序
        verbose_name = '文章'  # 指定后台显示模型名称
        verbose_name_plural = '文章列表'  # 指定后台显示模型复数名称
        db_table = 'article'
        get_latest_by = 'created_time'

apps/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Article, Category, Tag
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import Http404
from django.conf import settings

categories = Category.objects.all()  # 获取全部的分类对象
tags = Tag.objects.all()  # 获取全部的标签对象


def home(request):  # 主页
    posts = Article.objects.all()  # 获取全部的Article对象
    paginator = Paginator(posts, settings.PAGE_NUM)  # 每页显示数量，对应在setting.py中的PAGE_NUM
    page = request.GET.get('page')  # 获取url中的page参数值
    try:
        post_list = paginator.page(page)
    except PageNotAnInteger:
        post_list = paginator.page(1)
    except EmptyPage:
        post_list = paginator.page(paginator.num_pages)
    return render(request, 'blog/home.html', {'post_list': post_list, 'category_list': categories})


def detail(request, pk):  # 查看文章详情
    post = get_object_or_404(Article, pk=pk)
    post.viewed()  # 更新浏览次数
    tags = post.tags.all()  # 获取文章对应所有标签
    next_post = post.next_article()  # 上一篇对象
    prev_post = post.prev_article()  # 上一篇对象
    return render(
        request, 'blog/post.html',
        {
            'post': post,
            'tags': tags,
            'category_list': categories,
            'next_post': next_post,
            'prev_post': prev_post,
        })


def search_category(request, pk):  # 分类搜索
    posts = Article.objects.filter(category_id=pk)
    category = get_object_or_404(Category, pk=pk)
    paginator = Paginator(posts, settings.PAGE_NUM)  # 每页显示数量
    try:
        page = request.GET.get('page')
        post_list = paginator.page(page)
    except PageNotAnInteger:
        post_list = paginator.page(1)
    except EmptyPage:
        post_list = paginator.page(paginator.num_pages)
    return render(
        request, 'blog/category.html',
        {
            'post_list': post_list,
            'category_list': categories,
            'category': category
        })


def search_tag(request, tag):  # 标签搜索
    posts = Article.objects.filter(tags__name__contains=tag)

    paginator = Paginator(posts, settings.PAGE_NUM)  # 每页显示数量
    try:
        page = request.GET.get('page')  # 获取URL中page参数的值
        post_list = paginator.page(page)
    except PageNotAnInteger:
        post_list = paginator.page(1)
    except EmptyPage:
        post_list = paginator.page(paginator.num_pages)
    return render(request, 'blog/tag.html', {'post_list': post_list, 'category_list': categories, 'tag': tag})


def archives(request, year, month, day):
    posts = Article.objects.filter(pub_time__year=year, pub_time__month=month, pub_time__day=day).order_by('-pub_time')
    paginator = Paginator(posts, settings.PAGE_NUM)  # 每页显示数量
    try:
        page = request.GET.get('page')  # 获取URL中page参数的值
        post_list = paginator.page(page)
    except PageNotAnInteger:
        post_list = paginator.page(1)
    except EmptyPage:
        post_list = paginator.page(paginator.num_pages)
    return render(request, 'blog/archive.html', {
        'post_list': post_list,
        'category_list': categories,
        'months': months,
        'year_month_day': year + '年' + month + '月' + day + '日'
    })

apps/blog/templates/blog/archive.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <h1 class="content-subhead">归档:&nbsp;{{ year_month_day }}</h1>
    <div class="blog-post">
        {% for post in post_list %}
            <div class="post-container">
                <section class="post">
                    <header class="post-header">
                        <img width="48" height="48" alt="Tilo Mitra's avatar" class="post-avatar"
                             src='{% static "image/avatar.png" %}'>
                        <h2 class="post-title"><a href="{% url 'blog:article_detail' post.id %}"
                                                  style="text-decoration: none">{{ post.title }}</a></h2>
                        <p class="post-meta">
                            <i class="fa fa-calendar" aria-hidden="true"></i>&nbsp;{{ post.pub_time |date:'Y-m-d' }}&nbsp;&nbsp;
                            <i class="fa fa-eye" aria-hidden="true"></i>&nbsp;{{ post.views }}次浏览&nbsp;&nbsp;
                            <i class="fa fa-book"></i>&nbsp;{{ post.category }}&nbsp;&nbsp;
                        </p>
                    </header>

                    <div class="post-description">
                        <p>
                            {#striptags用于过滤正文中所有的HTML标签#}
                            {#truncatechars用于截取正文前300个字符#}
                            {{ post.content|striptags|truncatechars:300 }}
                        </p>
                    </div>
                    <div>
                        <a class="post-category post-category-design" href="{% url 'blog:article_detail' post.id %}"
                           style="text-decoration: none">阅读全文</a>
                    </div>
                </section>
            </div>
        {% endfor %}
    </div><!-- /.blog-post -->
    {% if post_list.object_list and post_list.paginator.num_pages > 1 %}
        <div>
            {% if post_list.has_previous %}
                <a class="footer" href="?page={{ post_list.previous_page_number }}"
                   style="text-decoration: none; float: left; padding-left: 1%">
                    <i class="fa fa-angle-left"></i>&nbsp;&nbsp;上一页
                </a>
            {% endif %}
            {% if post_list.has_next %}
                <a class="footer" href="?page={{ post_list.next_page_number }}"
                   style="text-decoration: none; float: right; padding-right: 1%">
                    下一页&nbsp;&nbsp;<i class="fa fa-angle-right"></i>
                </a>
            {% endif %}
        </div>
    {% endif %}
{% endblock %}

apps/blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} jbt Blog {% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/pure-min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/grids-responsive-min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/blog.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}"/>
</head>
<body>
<div id="layout" class="pure-g">
    <!--左侧边栏 开始-->
    <div class="sidebar pure-u-1 pure-u-md-1-4">
        <div class="header">
            <h1 class="brand-title"><a href="{% url 'home' %}" style="text-decoration: none">金笔头博客</a></h1>
            <br>
            <h2 class="brand-tagline">Love Learning, Love Sharing...</h2>
            <br>
            <nav class="nav">
                <ul class="nav-list">
                    <li class="nav-item">
                        {% for category in category_list %}
                            <a class="pure-button" href="{% url 'category_menu' id=category.id %}"
                               style="text-decoration: none">{{ category }}</a>
                        {% endfor %}&nbsp;
                    </li>
                </ul>
                <br>
                <h3 class="brand-tagline" style="margin: 2%">文章归档</h3>
                <ul class="nav-list" style="margin: 2%">
                    {% for m in months %}
                        <li>
                            <a href="{% url 'blog:archives' year=m.year month=m.month %}"
                               style="text-decoration: none">{{ m | date:'Y年m月' }}</a>
                        </li>
                    {% empty %}
                        暂无归档！
                    {% endfor %}
                </ul>
                <br>
                <ul class="nav-list">
                <li>
                    <a href="#" style="text-decoration: none">
                        <i class="fa fa-weixin" style="font-size: 30px" aria-hidden="true" title="微信公众号"></i>
                    </a>
                    &nbsp;
                    <a href=mailto:jinbitou@126.com style="text-decoration: none">
                        <i class="fa fa-envelope-o" style="font-size: 30px" aria-hidden="true" title="邮箱"></i>
                    </a>
                    &nbsp;
                    <a href="https://github.com/leeyis/" style="text-decoration: none" title="Github"
                       target="_blank">
                        <i class="fa fa-github" style="font-size: 34px" aria-hidden="true"></i>
                    </a>
                    &nbsp;
                </li>
            </ul>
            </nav>
        </div>
    </div>
    <!--左侧边栏 结束-->
    <!--文章列表 开始-->
    <div class="content pure-u-1 pure-u-md-3-4">
        <div>
            {% block content %}
            {% endblock %}
        </div>
    </div>
    <!--文章列表 结束-->
</div>
<div class="go-top">
    <div class="arrow"></div>
    <div class="stick"></div>
</div>
<script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script>
    $(function () {
        $(window).scroll(function () {
            if ($(window).scrollTop() > 1000)
                $('div.go-top').show();
            else
                $('div.go-top').hide();
        });
        $('div.go-top').click(function () {
            $('html, body').animate({scrollTop: 0}, 500);
        });
    });
</script>
</body>
</html>

apps/blog/templates/blog/category.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <h1 class="content-subhead">分类:&nbsp;{{ category }}</h1>
    <div class="blog-post">
        {% for post in post_list %}
            <div class="post-container">
                <section class="post">
                    <header class="post-header">
                        <img width="48" height="48" alt="Tilo Mitra's avatar" class="post-avatar"
                             src='{% static "image/avatar.png" %}'>
                        <h2 class="post-title"><a href="{% url 'blog:article_detail' post.id %}"
                                                  style="text-decoration: none">{{ post.title }}</a></h2>
                        <p class="post-meta">
                            <i class="fa fa-calendar" aria-hidden="true"></i>&nbsp;{{ post.pub_time |date:'Y-m-d' }}&nbsp;&nbsp;
                            <i class="fa fa-eye" aria-hidden="true"></i>&nbsp;{{ post.views }}次浏览&nbsp;&nbsp;
                            <i class="fa fa-book"></i>&nbsp;{{ post.category }}&nbsp;&nbsp;
                        </p>
                    </header>

                    <div class="post-description">
                        <p>
                            {#striptags用于过滤正文中所有的HTML标签#}
                            {#truncatechars用于截取正文前300个字符#}
                            {{ post.content|striptags|truncatechars:300 }}
                        </p>
                    </div>
                    <div>
                        <a class="post-category post-category-design" href="{% url 'blog:article_detail' post.id %}"
                           style="text-decoration: none">阅读全文</a>
                    </div>
                </section>
            </div>
        {% endfor %}
    </div><!-- /.blog-post -->
    {% if post_list.object_list and post_list.paginator.num_pages > 1 %}
        <div>
            {% if post_list.has_previous %}
                <a class="footer" href="?page={{ post_list.previous_page_number }}"
                   style="text-decoration: none; float: left; padding-left: 1%">
                    <i class="fa fa-angle-left"></i>&nbsp;&nbsp;上一页
                </a>
            {% endif %}
            {% if post_list.has_next %}
                <a class="footer" href="?page={{ post_list.next_page_number }}"
                   style="text-decoration: none; float: right; padding-right: 1%">
                    下一页&nbsp;&nbsp;<i class="fa fa-angle-right"></i>
                </a>
            {% endif %}
        </div>
    {% endif %}
{% endblock %}

apps/blog/templates/blog/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="posts">
        {% for post in post_list %}
            <div class="post-container">
                <section class="post">
                    <header class="post-header">
                        <img width="48" height="48" alt="Tilo Mitra's avatar" class="post-avatar"
                             src='{% static "image/avatar.png" %}'>
                        <h2 class="post-title"><a href="{% url 'blog:article_detail' post.id %}"
                                                  style="text-decoration: none">{{ post.title }}</a></h2>
                        <p class="post-meta">
                            <i class="fa fa-calendar" aria-hidden="true"></i>&nbsp;{{ post.pub_time |date:'Y-m-d' }}&nbsp;&nbsp;
                            <i class="fa fa-eye" aria-hidden="true"></i>&nbsp;{{ post.views }}次浏览&nbsp;&nbsp;
                            <i class="fa fa-book"></i>&nbsp;{{ post.category }}&nbsp;&nbsp;
                        </p>
                    </header>

                    <div class="post-description">
                        <p>
                            {#striptags用于过滤正文中所有的HTML标签#}
                            {#truncatechars用于截取正文前300个字符#}
                            {{ post.content|striptags|truncatechars:300 }}
                        </p>
                    </div>
                    <div>

                        <a class="button" href="{% url 'blog:article_detail' post.id %}"
                           style="text-decoration: none">阅读全文</a>
                    </div>

                </section>
            </div>
        {% endfor %}
    </div><!-- /.blog-post -->
    {% if post_list.object_list and post_list.paginator.num_pages > 1 %}
        <div>
            {% if post_list.has_previous %}
                <a class="footer" href="?page={{ post_list.previous_page_number }}"
                   style="text-decoration: none; float: left; padding-left: 1%">
                    <i class="fa fa-angle-left"></i>&nbsp;&nbsp;上一页
                </a>
            {% endif %}
            {% if post_list.has_next %}
                <a class="footer" href="?page={{ post_list.next_page_number }}"
                   style="text-decoration: none; float: right; padding-right: 1%">
                    下一页&nbsp;&nbsp;<i class="fa fa-angle-right"></i>
                </a>
            {% endif %}
        </div>
    {% endif %}
{% endblock %}   

apps/blog/templates/blog/post.html
{% extends "base.html" %}
{% block content %}
    <div class="posts">
        <section class="post">
            <header class="post-header">
                <h2 class="post-title"><a href="{% url 'blog:article_detail' post.id %}"
                                          style="text-decoration: none">{{ post.title }}</a></h2>
                <p class="post-meta">
                    <i class="fa fa-calendar" aria-hidden="true"></i>&nbsp; {{ post.pub_time|date:'Y-m-d H:i' }}&nbsp;&nbsp;
                    <i class="fa fa-book"></i>&nbsp;
                    <a href=""
                       style="text-decoration: none">{{ post.category }}</a>&nbsp;&nbsp;
                    <i class="fa fa-tags" aria-hidden="true"></i>
                    {% for tag in tags %}
                        <a href="{% url 'blog:search_tag' tag %}"
                           style="text-decoration: none">{{ tag }}</a>
                    {% endfor %}&nbsp;&nbsp;
                    <i class="fa fa-eye" aria-hidden="true"></i>&nbsp;{{ post.views }}次浏览
                </p>
            </header>

            <div class="post-description">
                <p>
                    {{ post.content |safe }}
                </p>
            </div>
        </section>
    </div><!-- /.blog-post -->
    <!-- 上下篇文章切换 -->
    <div>
        {% if prev_post %}
            <a class="footer" href="{% url 'blog:article_detail' prev_post.id %}" style="text-decoration: none; float: left;">
                <i class="fa fa-angle-left"></i>&nbsp;&nbsp;上一篇：{{ prev_post.title }}
            </a>
        {% endif %}
        {% if next_post %}
            <a class="footer" href="{% url 'blog:article_detail' next_post.id %}" style="text-decoration: none; float: right;">
                下一篇：{{ next_post.title }}&nbsp;&nbsp;
                <i class="fa fa-angle-right"></i>
            </a>
        {% endif %}
    </div>

{% endblock %}

apps/blog/templates/blog/tag.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <h1 class="content-subhead">标签:&nbsp;{{ tag }}</h1>
    <div class="blog-post">
        {% for post in post_list %}
            <div class="post-container">
                <section class="post">
                    <header class="post-header">
                        <img width="48" height="48" alt="Tilo Mitra's avatar" class="post-avatar"
                             src='{% static "image/avatar.png" %}'>
                        <h2 class="post-title"><a href="{% url 'blog:article_detail' post.id %}"
                                                  style="text-decoration: none">{{ post.title }}</a></h2>
                        <p class="post-meta">
                            <i class="fa fa-calendar" aria-hidden="true"></i>&nbsp;{{ post.pub_time |date:'Y-m-d' }}&nbsp;&nbsp;
                            <i class="fa fa-eye" aria-hidden="true"></i>&nbsp;{{ post.views }}次浏览&nbsp;&nbsp;
                            <i class="fa fa-book"></i>&nbsp;{{ post.category }}&nbsp;&nbsp;
                        </p>
                    </header>

                    <div class="post-description">
                        <p>
                            {#striptags用于过滤正文中所有的HTML标签#}
                            {#truncatechars用于截取正文前300个字符#}
                            {{ post.content|striptags|truncatechars:300 }}
                        </p>
                    </div>
                    <div>
                        <a class="post-category post-category-design" href="{% url 'blog:article_detail' post.id %}"
                           style="text-decoration: none">阅读全文</a>
                    </div>
                </section>
            </div>
        {% endfor %}
    </div><!-- /.blog-post -->
    {% if post_list.object_list and post_list.paginator.num_pages > 1 %}
        <div>
            {% if post_list.has_previous %}
                <a class="footer" href="?page={{ post_list.previous_page_number }}"
                   style="text-decoration: none; float: left; padding-left: 1%">
                    <i class="fa fa-angle-left"></i>&nbsp;&nbsp;上一页
                </a>
            {% endif %}
            {% if post_list.has_next %}
                <a class="footer" href="?page={{ post_list.next_page_number }}"
                   style="text-decoration: none; float: right; padding-right: 1%">
                    下一页&nbsp;&nbsp;<i class="fa fa-angle-right"></i>
                </a>
            {% endif %}
        </div>
    {% endif %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} jbt Blog {% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/pure-min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/grids-responsive-min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/blog.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}"/>
</head>
<body>
<div id="layout" class="pure-g">
    <!--左侧边栏 开始-->
    <div class="sidebar pure-u-1 pure-u-md-1-4">
        <div class="header">
            <h1 class="brand-title"><a href="/" style="text-decoration: none">金笔头博客</a></h1>
            <br>
            <h2 class="brand-tagline">Love Learning, Love Sharing...</h2>
            <br>
            <nav class="nav">
                <ul class="nav-list">
                    <li class="nav-item">
                        {% for category in category_list %}
                            <a class="pure-button" href="{% url 'blog:search_category' category.id %}"
                               style="text-decoration: none">{{ category }}</a>
                        {% endfor %}&nbsp;
                    </li>
                </ul>
                <br>
                <h3 class="brand-tagline" style="margin: 2%">文章归档</h3>
                <ul class="nav-list" style="margin: 2%">
                    {% for m in months %}
                        <li>
                            <a href="{% url 'archives' year=m.year month=m.month %}"
                               style="text-decoration: none">{{ m | date:'Y年m月' }}</a>
                        </li>
                    {% empty %}
                        暂无归档！
                    {% endfor %}
                </ul>
                <br>
                <ul class="nav-list">
                <li>
                    <a href="#" style="text-decoration: none">
                        <i class="fa fa-weixin" style="font-size: 30px" aria-hidden="true" title="微信公众号"></i>
                    </a>
                    &nbsp;
                    <a href=mailto:jinbitou@126.com style="text-decoration: none">
                        <i class="fa fa-envelope-o" style="font-size: 30px" aria-hidden="true" title="邮箱"></i>
                    </a>
                    &nbsp;
                    <a href="https://github.com/leeyis/" style="text-decoration: none" title="Github"
                       target="_blank">
                        <i class="fa fa-github" style="font-size: 34px" aria-hidden="true"></i>
                    </a>
                    &nbsp;
                </li>
            </ul>
            </nav>
        </div>
    </div>
    <!--左侧边栏 结束-->
    <!--文章列表 开始-->
    <div class="content pure-u-1 pure-u-md-3-4">
        <div>
            {% block content %}
            {% endblock %}
        </div>
    </div>
    <!--文章列表 结束-->
</div>
<div class="go-top">
    <div class="arrow"></div>
    <div class="stick"></div>
</div>
<script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script>
    $(function () {
        $(window).scroll(function () {
            if ($(window).scrollTop() > 1000)
                $('div.go-top').show();
            else
                $('div.go-top').hide();
        });
        $('div.go-top').click(function () {
            $('html, body').animate({scrollTop: 0}, 500);
        });
    });
</script>
</body>
</html>